/*
    The mayor's office layouts authored in Altis's towns (OT_fnc_officeLayout). Generated by
    tools/officegen/merge_layouts.py from tools/officegen/layouts/Altis.txt: don't edit by hand.
*/

createHashMapFromArray [
]
