/*
    Description:
    A mayor's office defence template: what each of the five defence tiers adds to a building, in
    its model coordinates (tier N in play is tiers 1..N together, OT_fnc_officeApplyTemplate). The
    templates are the OT_fnc_officeTpl_<key> functions (functions/offices/templates, generated by
    tools/officegen), one per building model; a key with no function yet gives []. Any machine.

    Parameters:
        _this # 0: STRING - Template key (OT_fnc_officeTemplateKey)

    Usage: private _tiers = ["i_House_Big_01_V1_F"] call OT_fnc_officeTemplate;

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
        kind "guard" (class or role: "gendarme", "rifleman", "autorifleman", "marksman", "at", "mg_gunner", "officer")
        or "object" (an object class); extra flags: "outside" (stands on the ground outside), "flag" (gets the occupier's flag).
        [] when there is no template for the key
*/

params [["_key", "", [""]]];

if (_key isEqualTo "") exitWith { [] };
private _fnc = missionNamespace getVariable [format ["OT_fnc_officeTpl_%1", _key], {}];
private _tiers = call _fnc;
if (isNil "_tiers" || { !(_tiers isEqualType []) } || { (count _tiers) isNotEqualTo 5 }) exitWith { [] };
_tiers
