/*
    The occupier compounds' areas in Altis's towns (OT_fnc_officeCompound): per town, the tier 3, 4 and 5
    polygons (world [x, y], [] for a tier without one). Generated by tools/officegen/merge_compounds.py from
    tools/officegen/compounds/Altis.txt: don't edit by hand.
*/

createHashMapFromArray [
    ["Rodopoli", [[[18691.98,16597.27],[18730.88,16624.87],[18739.18,16618.97],[18748.68,16605.77],[18748.88,16593.57],[18741.38,16588.07],[18713.58,16568.07],[18697.88,16588.97]], [[18691.98,16597.27],[18730.88,16624.87],[18739.18,16618.97],[18748.68,16605.77],[18755.18,16598.27],[18766.68,16581.37],[18746.78,16567.77],[18732.78,16569.27],[18717.98,16558.97],[18713.78,16565.07],[18713.58,16568.07],[18697.88,16588.97]], []]]
]
