/*
    The occupier compounds' areas in Altis's towns (OT_fnc_officeCompound): per town, the tier 3, 4 and 5
    polygons (world [x, y], [] for a tier without one). Generated by tools/officegen/merge_compounds.py from
    tools/officegen/compounds/Altis.txt: don't edit by hand.
*/

createHashMapFromArray [
    ["Rodopoli", [[[18691.98,16597.27],[18733.93,16626.53],[18746.86,16604.96],[18743.12,16602.54],[18744.90,16599.10],[18748.88,16593.57],[18741.38,16588.07],[18713.58,16568.07],[18697.88,16588.97]], [[18691.98,16597.27],[18733.03,16626.59],[18738.16,16618.64],[18745.85,16606.83],[18751.50,16597.77],[18765.21,16577.03],[18749.27,16566.48],[18735.51,16557.43],[18724.70,16550.30],[18712.17,16567.17],[18713.58,16568.07],[18697.88,16588.97]], []]]
]
