/*
    Description:
    Mayor's office defence template for Land_i_House_Big_02_V1_F (and the classes OT_fnc_officeTemplateKey maps
    to "i_House_Big_02_V1_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 2/4/6/8/10.
    Generated by tools/officegen/gen_templates.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
        (kind "doorway": a marker of a real entrance for the checks, nothing is spawned for it)
*/

[
    // Tier 1: the doorways, the office, the flag, the gendarmes
    [
        ["doorway", "main", [-4.65, -6.17, -2.5], 270, [3.5, 0]],
        ["doorway", "side", [0.1, 5.3, -2.5], 0, [1.25, 2]],
        ["object", "Land_TableDesk_F", [-2.4, 2, 1], 270, []],
        ["object", "Land_OfficeChair_01_F", [-4, 2, 1], 270, []],
        ["object", "Land_MapBoard_F", [-4.35, 4, 1], 90, []],
        ["object", "Flag_NATO_F", [-5.65, -9.47, -2.5], 270, ["outside", "flag"]],
        ["guard", "gendarme", [0.1, -3.3, -2.5], 238.82, []],
        ["guard", "gendarme", [3.5, -5.7, -2.5], 180, []]
    ],
    // Tier 2: the nest at the main door with the military pair, pairs of bags at the side doors
    [
        ["object", "Land_BagFence_Long_F", [-7.65, -6.18, -2.5], 270, ["outside", "axis"]],
        ["object", "Land_BagFence_Short_F", [-6.7, -7.88, -2.5], 0, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-6.7, -4.47, -2.5], 0, ["outside"]],
        ["guard", "rifleman", [-6.52, -6.77, -2.5], 270, ["outside"]],
        ["guard", "autorifleman", [-6.52, -5.58, -2.5], 270, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-1.9, 6.5, -2.5], 0, ["outside"]],
        ["object", "Land_BagFence_Short_F", [2.1, 6.5, -2.5], 0, ["outside"]]
    ],
    // Tier 3: the back door's post, firing posts at the side doors, window posts
    [
        ["object", "Land_HBarrier_3_F", [-7.15, -10.38, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-7.15, -1.98, -2.5], 270, ["outside"]],
        ["guard", "rifleman", [4.1, 2.88, -2.5], 90, ["free"]],
        ["object", "Land_HBarrier_3_F", [4.3, 7.9, -2.5], 0, ["outside"]],
        ["guard", "autorifleman", [4.3, 6.4, -2.5], 0, ["outside"]]
    ],
    // Tier 4: wire on the doorless sides, the stoppers on the approach, the gunner on the balcony, an upstairs post
    [
        ["object", "Land_Razorwire_F", [0.5, -9, -2.5], 180, ["outside"]],
        ["object", "Land_Razorwire_F", [8, 0.5, -2.5], 90, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-17.65, -6.18, -2.5], 270, ["outside", "axis"]],
        ["object", "Land_CzechHedgehog_01_F", [-16.85, -8.98, -2.5], 315, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [-16.85, -3.38, -2.5], 315, ["outside"]],
        ["guard", "mg_gunner", [-4, -5, 1], 270, ["free"]],
        ["guard", "rifleman", [4.2, 2.9, 1], 90, []]
    ],
    // Tier 5: the perimeter and its gate with the AT man, the airlock, the office's cover, the marksman
    [
        ["object", "Land_HBarrier_5_F", [-20.65, -11, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-14.64, -11, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.63, -11, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-2.62, -11, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [3.39, -11, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [8.2, -11, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-20.65, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-14.64, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.63, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-2.62, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [3.39, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_3_F", [8.2, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, -6.78, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, -0.74, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, 5.3, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [10, 8.94, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [10, 10.18, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-23.65, -9.3, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23.65, 0.27, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23.65, 6.4, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-23.65, 10.13, -2.5], 270, ["outside"]],
        ["object", "Land_BarGate_F", [-23.65, -5.8, -2.5], 270, ["outside", "axis", "gate"]],
        ["object", "Land_BagFence_Long_F", [-0.2, 2, 1], 90, []],
        ["guard", "at", [-22.15, -1.6, -2.5], 270, ["outside"]],
        ["guard", "marksman", [-0.6, -5.3, 1], 180, []]
    ]
]
