/*
    Description:
    Mayor's office defence template for Land_i_Stone_HouseBig_V1_F (and the classes OT_fnc_officeTemplateKey maps
    to "i_Stone_HouseBig_V1_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 2/4/6/8/10.
    Generated by tools/officegen/gen_templates.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
        (kind "doorway": a marker of a real entrance for the checks, nothing is spawned for it)
*/

[
    // Tier 1: the doorways, the office, the flag, the gendarmes
    [
        ["doorway", "main", [3, -2, -1.4], 180, [1, -1]],
        ["object", "Land_TableDesk_F", [1, 0.4, -1.4], 0, []],
        ["object", "Land_OfficeChair_01_F", [1, 2, -1.4], 0, []],
        ["object", "Land_MapBoard_F", [1, -1.35, -1.4], 0, []],
        ["object", "Flag_NATO_F", [6.3, -3, -1.4], 180, ["outside", "flag"]],
        ["guard", "gendarme", [3.8, 1.7, -1.3], 90, []],
        ["guard", "gendarme", [-0.4, 2.3, -1.3], 141.67, []]
    ],
    // Tier 2: the nest at the main door with the military pair, pairs of bags at the side doors
    [
        ["object", "Land_BagFence_Long_F", [3, -5, -1.4], 180, ["outside", "axis"]],
        ["object", "Land_BagFence_Short_F", [4.7, -4.05, -1.4], 270, ["outside"]],
        ["object", "Land_BagFence_Short_F", [1.3, -4.05, -1.4], 270, ["outside"]],
        ["guard", "rifleman", [3.6, -3.88, -1.4], 180, ["outside"]],
        ["guard", "autorifleman", [2.4, -3.88, -1.4], 180, ["outside"]]
    ],
    // Tier 3: the back door's post, firing posts at the side doors, window posts
    [
        ["guard", "rifleman", [2.3, -0.8, 1.5], 180, []],
        ["guard", "autorifleman", [-0.6, 5, -1.4], 0, []]
    ],
    // Tier 4: wire on the doorless sides, the stoppers on the approach, the gunner on the balcony, an upstairs post
    [
        ["object", "Land_Razorwire_F", [2, 9, -1.4], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [9, 2, -1.4], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [-5, 2, -1.4], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [3, -15, -1.4], 180, ["outside", "axis"]],
        ["object", "Land_CzechHedgehog_01_F", [5.8, -14.2, -1.4], 225, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [0.2, -14.2, -1.4], 225, ["outside"]],
        ["guard", "mg_gunner", [6, 1, 1.4], 180, ["free"]],
        ["guard", "rifleman", [4.1, 4.8, 1.4], 270, []]
    ],
    // Tier 5: the perimeter and its gate with the AT man, the airlock, the office's cover, the marksman
    [
        ["object", "Land_HBarrier_5_F", [-3.25, -21, -1.4], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [8.25, -21, -1.4], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-3.48, 10.5, -1.4], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [2.57, 10.5, -1.4], 0, ["outside"]],
        ["object", "Land_HBarrier_3_F", [7.42, 10.5, -1.4], 0, ["outside"]],
        ["object", "Land_HBarrier_1_F", [9.88, 10.5, -1.4], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10.5, -16.78, -1.4], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10.5, -10.72, -1.4], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10.5, -4.67, -1.4], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10.5, 1.37, -1.4], 90, ["outside"]],
        ["object", "Land_HBarrier_3_F", [10.5, 6.22, -1.4], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [10.5, 8.68, -1.4], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-6.5, -16.78, -1.4], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-6.5, -10.72, -1.4], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-6.5, -4.67, -1.4], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-6.5, 1.37, -1.4], 270, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-6.5, 6.22, -1.4], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-6.5, 8.68, -1.4], 270, ["outside"]],
        ["object", "Land_BarGate_F", [3, -21, -1.4], 180, ["outside", "axis", "gate"]],
        ["object", "Land_BagFence_Short_F", [4.4, 0.2, -1.4], 0, []],
        ["guard", "at", [-1.2, -19.5, -1.4], 180, ["outside"]],
        ["guard", "marksman", [-0.9, 3.2, 1.5], 0, []]
    ]
]
