/*
    Description:
    Mayor's office defence template for Land_i_Shop_02_V1_F (and the classes OT_fnc_officeTemplateKey maps
    to "i_Shop_02_V1_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 3/5/7/9/11.
    Generated by tools/officegen/gen_templates.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
        (kind "doorway": a marker of a real entrance for the checks, nothing is spawned for it)
*/

[
    // Tier 1: the doorways, the office, the flag, the gendarmes
    [
        ["doorway", "main", [-5.9, -3.2, -2.6], 270, [1.25, 0]],
        ["object", "Land_TableDesk_F", [1, -2.4, -2.6], 180, []],
        ["object", "Land_OfficeChair_01_F", [1, -4, -2.6], 180, []],
        ["object", "Land_MapBoard_F", [3.35, -3, -2.6], 270, []],
        ["object", "Flag_NATO_F", [-6.9, -6.5, -2.6], 270, ["outside", "flag"]],
        ["guard", "gendarme", [-1.4, -0.7, -2.6], 240.95, []],
        ["guard", "gendarme", [-2.2, 3.9, -2.6], 0, []],
        ["guard", "gendarme", [-4.8, -2.9, 1.3], 270, []]
    ],
    // Tier 2: the nest at the main door with the military pair, pairs of bags at the side doors
    [
        ["object", "Land_BagFence_Long_F", [-8.9, -3.2, -2.6], 270, ["outside", "axis"]],
        ["object", "Land_BagFence_Short_F", [-7.95, -4.9, -2.6], 0, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-7.95, -1.5, -2.6], 0, ["outside"]],
        ["guard", "rifleman", [-7.78, -3.8, -2.6], 270, ["outside"]],
        ["guard", "autorifleman", [-7.78, -2.6, -2.6], 270, ["outside"]]
    ],
    // Tier 3: the back door's post, firing posts at the side doors, window posts
    [
        ["guard", "rifleman", [-5.1, -1.25, -2.6], 270, ["free"]],
        ["guard", "autorifleman", [-5.1, 0.25, -2.6], 270, ["free"]]
    ],
    // Tier 4: wire on the doorless sides, the stoppers on the approach, the gunner on the balcony, an upstairs post
    [
        ["object", "Land_Razorwire_F", [-1, -8, -2.6], 180, ["outside"]],
        ["object", "Land_Razorwire_F", [-1, 8, -2.6], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [8, 0, -2.6], 90, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-18.9, -3.2, -2.6], 270, ["outside", "axis"]],
        ["object", "Land_CzechHedgehog_01_F", [-18.1, -6, -2.6], 315, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [-18.1, -0.4, -2.6], 315, ["outside"]],
        ["guard", "mg_gunner", [-7, -1, 1.3], 270, ["free"]],
        ["guard", "rifleman", [-5.1, 3.12, 1.3], 270, ["free"]]
    ],
    // Tier 5: the perimeter and its gate with the AT man, the airlock, the office's cover, the marksman
    [
        ["object", "Land_HBarrier_5_F", [-21.83, -9.5, -2.6], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-15.7, -9.5, -2.6], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9.57, -9.5, -2.6], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-3.43, -9.5, -2.6], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [2.7, -9.5, -2.6], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [7.63, -9.5, -2.6], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-21.83, 9.5, -2.6], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-15.7, 9.5, -2.6], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9.57, 9.5, -2.6], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-3.43, 9.5, -2.6], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [2.7, 9.5, -2.6], 0, ["outside"]],
        ["object", "Land_HBarrier_3_F", [7.63, 9.5, -2.6], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [9.5, -5.33, -2.6], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [9.5, 0.62, -2.6], 90, ["outside"]],
        ["object", "Land_HBarrier_3_F", [9.5, 5.38, -2.6], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [9.5, 7.72, -2.6], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-24.9, -7.25, -2.6], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-24.9, 2.82, -2.6], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-24.9, 6.45, -2.6], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-24.9, 7.68, -2.6], 270, ["outside"]],
        ["object", "Land_BarGate_F", [-24.9, -3.2, -2.6], 270, ["outside", "axis", "gate"]],
        ["object", "Land_BagFence_Short_F", [-3.7, -1.8, -2.6], 90, []],
        ["object", "Land_BagFence_Long_F", [1, -0.2, -2.6], 0, []],
        ["guard", "at", [-23.4, 1, -2.6], 270, ["outside"]],
        ["guard", "at", [-0.8, -3.8, 1.3], 180, []]
    ]
]
