/*
    Description:
    Mayor's office defence template for Land_Hospital_main_F (and the classes OT_fnc_officeTemplateKey maps
    to "Hospital_main_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 4/6/8/10/12.
    Positions are in the main building's model coordinates; the framework spawns the wings itself
    (OT_fnc_officeParts). The ground is an open undercroft and lobby, the terraces at z 7.6 are the roofs.
    Generated by tools/officegen/gen_templates.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
        (kind "doorway": a marker of a real entrance for the checks, nothing is spawned for it)
*/

[
    // Tier 1: the doorways, the office, the flag, the gendarmes
    [
        ["doorway", "side", [12.2, 19.8, -7.8], 180, [1.25, 0]],
        ["doorway", "main", [2.9, 16.43, -7.8], 270, [1, 1]],
        ["doorway", "side", [2.9, 8.12, -7.8], 270, [1, 2]],
        ["doorway", "side", [-3.58, -7.9, -7.8], 180, [1, 3]],
        ["doorway", "side", [-11.3, -21, -7.8], 180, [1.2, 4]],
        ["object", "Land_TableDesk_F", [-6.4, 13, -7.8], 270, []],
        ["object", "Land_OfficeChair_01_F", [-8, 13, -7.8], 270, []],
        ["object", "Land_MapBoard_F", [-8.35, 11, -7.8], 90, []],
        ["object", "Flag_NATO_F", [1.9, 20.93, -7.8], 270, ["outside", "flag"]],
        ["guard", "gendarme", [-4.2, 15.9, -7.8], 85.77, []],
        ["guard", "gendarme", [-4.2, 7.5, -7.8], 38.5, []],
        ["guard", "gendarme", [6.8, 4.6, -7.8], 90, []],
        ["guard", "gendarme", [-4.1, 0.3, -7.8], 23.47, []],
        ["object", "Land_CampingChair_V2_F", [-7.5, 8.6, -7.8], 90, []],
        ["object", "Land_CampingChair_V2_F", [-7.5, 9.8, -7.8], 90, []],
        ["object", "Land_WaterCooler_01_new_F", [-3.4, 18.6, -7.8], 270, []]
    ],
    // Tier 2: the nest at the main door with the military pair, pairs of bags at the side doors
    [
        ["object", "Land_BagFence_Long_F", [-0.1, 16.43, -7.8], 270, ["axis"]],
        ["object", "Land_BagFence_Short_F", [0.85, 14.73, -7.8], 0, []],
        ["object", "Land_BagFence_Short_F", [0.85, 18.12, -7.8], 0, ["outside"]],
        ["guard", "rifleman", [1.03, 15.83, -7.8], 270, ["free"]],
        ["guard", "autorifleman", [1.02, 17.03, -7.8], 270, ["free"]],
        ["object", "Land_BagFence_Short_F", [14.2, 18.6, -7.8], 180, ["outside"]],
        ["object", "Land_BagFence_Short_F", [10.2, 18.6, -7.8], 180, ["outside"]],
        ["object", "Land_BagFence_Short_F", [1.7, 6.12, -7.8], 270, []],
        ["object", "Land_BagFence_Short_F", [1.7, 10.12, -7.8], 270, []],
        ["object", "Land_BagFence_Short_F", [-1.58, -9.1, -7.8], 180, []],
        ["object", "Land_BagFence_Short_F", [-5.58, -9.1, -7.8], 180, []],
        ["object", "Land_BagFence_Short_F", [-9.3, -22.2, -7.8], 180, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-13.3, -22.2, -7.8], 180, ["outside"]]
    ],
    // Tier 3: the back door's post, firing posts at the side doors, window posts
    [
        ["object", "Land_HBarrier_3_F", [8, 17.2, -7.8], 180, ["outside"]],
        ["guard", "rifleman", [8, 18.7, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-15.5, -23.6, -7.8], 180, ["outside"]],
        ["guard", "autorifleman", [-15.5, -22.1, -7.8], 180, ["outside"]],
        ["object", "Land_CampingTable_F", [-4.1, -1.4, -7.8], 0, []],
        ["object", "Land_PortableLongRangeRadio_F", [-4.4, -1.4, -7.04], 0, []],
        ["object", "Land_Map_altis_F", [-3.7, -1.4, -7.04], 90, []],
        ["object", "Land_CampingChair_V2_F", [-2.8, -1.4, -7.8], 270, []],
        ["object", "MapBoard_altis_F", [-6.6, -0.6, -7.8], 90, []],
        ["object", "Land_OfficeCabinet_01_F", [-7.6, -3.5, -7.8], 90, []],
        ["object", "Land_OfficeCabinet_01_F", [-7.6, -4.3, -7.8], 90, []]
    ],
    // Tier 4: wire on the doorless sides, the stoppers on the approach, the gunner on the balcony, an upstairs post
    [
        ["object", "Land_Razorwire_F", [-36.2, 47, -7.8], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [-28.3, 47, -7.8], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [-20.4, 47, -7.8], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [-12.5, 47, -7.8], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [-4.6, 47, -7.8], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [3.3, 47, -7.8], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [11.2, 47, -7.8], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [18, -16.65, -7.8], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [18, -8.75, -7.8], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [18, -0.85, -7.8], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [18, 7.05, -7.8], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [18, 14.95, -7.8], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [18, 22.85, -7.8], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [18, 30.75, -7.8], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [18, 38.65, -7.8], 90, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-10.1, 16.42, -7.8], 270, ["outside", "axis"]],
        ["object", "Land_CzechHedgehog_01_F", [-9.3, 13.62, -7.8], 315, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [-9.3, 19.22, -7.8], 315, ["outside"]],
        ["guard", "mg_gunner", [4, 41, 5.7], 0, ["free"]],
        ["guard", "rifleman", [-36.1, -8.75, 7.6], 270, ["free"]]
    ],
    // Tier 5: the perimeter and its gate with the AT man, the airlock, the office's cover, the marksman
    [
        ["object", "Land_HBarrier_5_F", [-43.01, -28, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-37.02, -28, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-31.04, -28, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-25.06, -28, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-19.07, -28, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-13.09, -28, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-7.11, -28, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-1.12, -28, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [4.86, -28, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10.84, -28, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [16.83, -28, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [20.41, -28, -7.8], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-43.01, 50, -7.8], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-37.02, 50, -7.8], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-31.04, 50, -7.8], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-25.06, 50, -7.8], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-19.07, 50, -7.8], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-13.09, 50, -7.8], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-7.11, 50, -7.8], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-1.12, 50, -7.8], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [4.86, 50, -7.8], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10.84, 50, -7.8], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [16.83, 50, -7.8], 0, ["outside"]],
        ["object", "Land_HBarrier_1_F", [20.41, 50, -7.8], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [21, -23.8, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [21, -17.8, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [21, -11.8, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [21, -5.8, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [21, 0.2, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [21, 6.2, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [21, 12.2, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [21, 18.2, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [21, 24.2, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [21, 30.2, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [21, 36.2, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [21, 42.2, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_3_F", [21, 47, -7.8], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-46, -23.76, -7.8], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-46, -17.67, -7.8], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-46, -11.58, -7.8], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-46, -5.49, -7.8], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-46, 0.6, -7.8], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-46, 6.69, -7.8], 270, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-46, 11.58, -7.8], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-46, 22.47, -7.8], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-46, 28.57, -7.8], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-46, 34.66, -7.8], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-46, 40.76, -7.8], 270, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-46, 45.66, -7.8], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-46, 48.15, -7.8], 270, ["outside"]],
        ["object", "Land_BarGate_F", [-46, 16.43, -7.8], 270, ["outside", "axis", "gate"]],
        ["object", "Land_BagFence_Long_F", [-4.2, 13, -7.8], 90, []],
        ["guard", "at", [-44.5, 12.23, -7.8], 270, ["outside"]],
        ["guard", "at", [-38.25, -10.9, 7.6], 0, ["free"]]
    ]
]
