/*
    Description:
    Mayor's office defence template for Land_i_Stone_HouseBig_V1_F (and the classes OT_fnc_officeTemplateKey maps
    to "i_Stone_HouseBig_V1_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 2/4/6/8/10.
    Generated by tools/officegen/gen_templates.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
*/

[
    // Tier 1: guard posts
    [
        ["object", "Flag_NATO_F", [6.3, -3.6, -1.4], 180, ["outside", "flag"]],
        ["object", "Land_TableDesk_F", [2, 1.45, -1.4], 180, []],
        ["object", "Land_OfficeChair_01_F", [2, 2.25, -1.4], 180, []],
        ["guard", "gendarme", [3.8, 1.7, -1.3], 90, []],
        ["guard", "gendarme", [-0.4, 2.3, -1.3], 138.92, []]
    ],
    // Tier 2: sandbags at the doors, a military pair
    [
        ["object", "Land_BagFence_Short_F", [1, -3.2, -1.4], 180, ["outside"]],
        ["object", "Land_BagFence_Short_F", [5, -3.2, -1.4], 180, ["outside"]],
        ["guard", "rifleman", [2, -2.9, -1.4], 180, ["outside"]],
        ["guard", "autorifleman", [4, -2.9, -1.4], 180, ["outside"]]
    ],
    // Tier 3: barriers at the doors, firing positions inside, the fireteam
    [
        ["object", "Land_HBarrier_3_F", [0.6, -5, -1.4], 180, ["outside"]],
        ["guard", "rifleman", [-0.6, 5, -1.4], 0, []],
        ["guard", "autorifleman", [0.6, -3.7, -1.4], 180, ["outside"]]
    ],
    // Tier 4: wire, top floor positions, barricades on the approaches, the squad
    [
        ["object", "Land_Razorwire_F", [2, 9, -1.4], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [9, 2, -1.4], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [-5, 2, -1.4], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [5, -6.4, -1.4], 180, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [1.4, -8.2, -1.4], 180, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [3.5, -10, -1.4], 225, ["outside"]],
        ["guard", "mg_gunner", [-0.9, 3.2, 1.5], 0, []],
        ["guard", "rifleman", [4.1, 4.8, 1.4], 270, []]
    ],
    // Tier 5: the perimeter and its gate, reinforced rooms, the marksman and AT man
    [
        ["object", "Land_HBarrier_5_F", [-3.42, -13.6, -1.4], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [0.33, -13.6, -1.4], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [6.97, -13.6, -1.4], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [9.72, -13.6, -1.4], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-3.48, 10.5, -1.4], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [2.57, 10.5, -1.4], 0, ["outside"]],
        ["object", "Land_HBarrier_3_F", [7.42, 10.5, -1.4], 0, ["outside"]],
        ["object", "Land_HBarrier_1_F", [9.88, 10.5, -1.4], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10.5, -9.39, -1.4], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10.5, -3.36, -1.4], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10.5, 2.66, -1.4], 90, ["outside"]],
        ["object", "Land_HBarrier_3_F", [10.5, 7.49, -1.4], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-6.5, -9.39, -1.4], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-6.5, -3.36, -1.4], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-6.5, 2.66, -1.4], 270, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-6.5, 7.49, -1.4], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [0.4, -11.8, -1.4], 180, ["outside"]],
        ["object", "Land_BagFence_Short_F", [1.6, 0.6, -1.4], 0, []],
        ["object", "Land_BagFence_Short_F", [4.4, 0.6, -1.4], 0, []],
        ["guard", "marksman", [2.3, -0.8, 1.5], 180, []],
        ["guard", "at", [4.6, -12, -1.4], 180, ["outside"]]
    ]
]
