/*
    Description:
    Mayor's office defence template for Land_Offices_01_V1_F (the Altis 5-storey office block).
    Guards hold the entrance hall, the north lobby, the south windows of each floor, the top-floor
    corner office and from tier 4 the roof parapets; a reception desk sits inside the double door and
    the mayor's office (desk, cabinets) and a radio room are on the top floor. Fortifications flank the
    south double door and the north-west side door, and tier 5 adds a HESCO compound 5.5 m outside the
    bbox with its gate on the south, in line with the entrance.

    Generated by tools/officegen/gen_bigoffices.py from tools/officegen/probe_offices.txt; edit the
    generator, not this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions] (tiers apply cumulatively); an item is
        [kind ("guard" or "object"), object class or guard role, [x, y, z] in the building's model
        coordinates, direction relative to the building, extra]
*/

[
    [ // Tier 1: 4 guards, 13 objects in all
        ["guard", "gendarme", [12.1, -6.9, -6.7], 180, []],
        ["guard", "gendarme", [0.6, 7.6, -6.7], 0, []],
        ["guard", "gendarme", [4.1, -6.7, -3], 180, []],
        ["guard", "gendarme", [12.2, -0.3, 5], 90, []],
        ["object", "Land_TableDesk_F", [11.5, -3, -6.7], 180, []],
        ["object", "Land_OfficeChair_01_F", [11.5, -2.2, -6.7], 180, []],
        ["object", "Land_WaterCooler_01_new_F", [12.4, -1.4, -6.7], 270, []],
        ["object", "Land_CampingChair_V2_F", [-11, 5.1, -6.7], 0, []],
        ["object", "Land_CampingChair_V2_F", [-12, 5.1, -6.7], 0, []],
        ["object", "Land_OfficeCabinet_01_F", [-6, 4.95, -6.7], 0, []],
        ["object", "Land_OfficeCabinet_01_F", [-7, 4.95, -6.7], 0, []],
        ["object", "MapBoard_altis_F", [-15.3, 5.1, -6.7], 0, []],
        ["object", "Land_TableDesk_F", [10.8, -2.2, 5], 270, []],
        ["object", "Land_OfficeChair_01_F", [11.6, -2.2, 5], 270, []],
        ["object", "Land_OfficeCabinet_01_F", [9.4, 0.15, 5], 180, []],
        ["object", "Land_OfficeCabinet_01_F", [10.1, 0.15, 5], 180, []],
        ["object", "Land_OfficeCabinet_01_F", [8.95, -2, 5], 90, []]
    ],
    [ // Tier 2: 6 guards, 17 objects in all
        ["guard", "rifleman", [5.6, -7.1, -6.7], 180, []],
        ["guard", "autorifleman", [1.8, -6.7, 1], 180, []],
        ["object", "Land_BagFence_Round_F", [12.8, -10.3, -6.7], 180, ["outside"]],
        ["object", "Land_BagFence_Round_F", [8, -10.3, -6.7], 180, ["outside"]],
        ["object", "Land_BagFence_Round_F", [-17.2, 11, -6.7], 0, ["outside"]],
        ["object", "Land_BagFence_Round_F", [-12.4, 11, -6.7], 0, ["outside"]]
    ],
    [ // Tier 3: 8 guards, 32 objects in all
        ["guard", "rifleman", [6.6, -7, -3], 180, []],
        ["guard", "officer", [10.3, -7.1, 5], 180, []],
        ["object", "Land_HBarrier_3_F", [13.6, -12.3, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [7.2, -12.3, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-18, 13, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-11.6, 13, -6.7], 0, ["outside"]],
        ["object", "Land_BagFence_Short_F", [5.6, -8, -6.7], 180, []],
        ["object", "Land_BagFence_Short_F", [5.35, -7.4, -3], 180, []],
        ["object", "Land_BagFence_Short_F", [3.4, -7.4, 1], 180, []],
        ["object", "Land_BagFence_Short_F", [-0.3, -7.05, 1], 180, []],
        ["object", "Land_BagFence_Short_F", [12.45, -1.8, 5], 90, []],
        ["object", "Land_BagFence_Short_F", [11.9, -7.4, 5], 180, []],
        ["object", "Land_CampingTable_F", [5.3, 2.4, 5], 90, []],
        ["object", "Land_PortableLongRangeRadio_F", [5.3, 2.4, 5.76], 90, []],
        ["object", "Land_CampingChair_V2_F", [4.5, 2.4, 5], 90, []],
        ["object", "MapBoard_altis_F", [5.5, 3.9, 5], 180, []],
        ["object", OT_flag_NATO, [14.6, -10, -6.7], 0, ["outside"]]
    ],
    [ // Tier 4: 10 guards, 48 objects in all
        ["guard", "mg_gunner", [12.3, -7.2, 10.2], 135, []],
        ["guard", "rifleman", [-5.8, 7.3, 10.2], 0, []],
        ["object", "Land_Razorwire_F", [15.9, -13.7, -6.7], 180, ["outside"]],
        ["object", "Land_Razorwire_F", [4.9, -13.7, -6.7], 180, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [12.6, -15.3, -6.7], 225, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [8.2, -15.3, -6.7], 225, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [9.8, -17.5, -6.7], 205, ["outside"]],
        ["object", "Land_Razorwire_F", [-9.3, 14.4, -6.7], 0, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-19.3, 14.4, -6.7], 0, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [-17, 16, -6.7], 45, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [-12.6, 16, -6.7], 45, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-14.2, 18.2, -6.7], 25, ["outside"]],
        ["object", "Land_BagFence_Short_F", [12.3, -8.1, 10.2], 180, []],
        ["object", "Land_BagFence_Short_F", [13.1, -7.2, 10.2], 90, []],
        ["object", "Land_BagFence_Short_F", [-5.8, 8.3, 10.2], 0, []],
        ["object", "Land_BagFence_Short_F", [-16.9, -0.7, 10.2], 270, []],
        ["object", "Land_BagFence_Short_F", [12.9, -0.9, 10.2], 90, []],
        ["object", "Land_Ammobox_rounds_F", [11, -5.8, 10.2], 90, []]
    ],
    [ // Tier 5: 12 guards, 93 objects in all
        ["guard", "marksman", [4.6, -6.5, 10.2], 180, []],
        ["object", "Land_BagFence_Short_F", [4.6, -7.5, 10.2], 180, []],
        ["object", "Land_BagFence_Long_F", [2, -8, -6.7], 180, []],
        ["object", "Land_BagFence_Long_F", [-9, 8.1, -6.7], 0, []],
        ["object", "Land_BagFence_Long_F", [1.2, -7.05, -3], 180, []],
        ["object", "Land_BagFence_Short_F", [12.45, -3.6, 5], 90, []],
        ["object", "Land_BagFence_Short_F", [12.45, -5.5, 5], 90, []],
        ["object", "Land_BagFence_Corner_F", [4.6, -3.9, -6.7], 45, []],
        ["object", "Land_HBarrier_5_F", [-20.72, -19.8, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-15.56, -19.8, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-10.4, -19.8, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-5.25, -19.8, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-0.09, -19.8, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [5.07, -19.8, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [15.69, -19.8, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [20.76, -19.8, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [23.3, -16.97, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [23.3, -11.31, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [23.3, -5.66, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [23.3, 0, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [23.3, 5.66, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [23.3, 11.31, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [23.3, 16.97, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [20.39, 19.8, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [14.56, 19.8, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.74, 19.8, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [2.91, 19.8, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-2.91, 19.8, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.74, 19.8, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-14.56, 19.8, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-20.39, 19.8, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23.3, 16.97, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23.3, 11.31, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23.3, 5.66, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23.3, 0, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23.3, -5.66, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23.3, -11.31, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23.3, -16.97, -6.7], 270, ["outside"]],
        ["object", "Land_BagBunker_Small_F", [5.4, -17.5, -6.7], 180, ["outside"]],
        ["object", "Land_BagBunker_Small_F", [15.4, -17.5, -6.7], 180, ["outside"]],
        ["guard", "at", [5.4, -17.2, -6.7], 180, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [8.9, -19.8, -6.7], 210, ["outside"]],
        ["object", "Land_Razorwire_F", [3.4, -22, -6.7], 180, ["outside"]],
        ["object", "Land_Razorwire_F", [17.4, -22, -6.7], 180, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [7.8, -23.4, -6.7], 45, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [13, -23.4, -6.7], 45, ["outside"]],
        ["object", OT_flag_NATO, [-9, -10.5, 10.2], 0, []]
    ]
]
