/*
    Description:
    Mayor's office defence template for Land_i_Shop_01_V1_F (and the classes OT_fnc_officeTemplateKey maps
    to "i_Shop_01_V1_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 2/4/6/8/10.
    Altis small shop: the shop floor with a flat above and a balcony over the front porch;
    front double door and a back door. The flat is at z 1.2 (the probe's level 0.2 is the stair landing).
    Generated by tools/officegen/gen_shops.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
*/

[
    // Tier 1: guard posts
    [
        ["guard", "gendarme", [0, -3.6, -2.7], 180, ["outside"]],
        ["guard", "gendarme", [0.9, 4.2, -2.7], 180, []]
    ],
    // Tier 2: sandbags at the doors, a military pair
    [
        ["object", "Land_BagFence_Long_F", [2.15, -5.5, -2.7], 180, ["outside"]],
        ["object", "Land_BagFence_Short_F", [2.3, 10.45, -2.7], 0, ["outside"]],
        ["guard", "rifleman", [3.15, -4.6, -2.7], 180, ["outside"]],
        ["guard", "autorifleman", [2.3, 9.55, -2.7], 0, ["outside"]]
    ],
    // Tier 3: barriers at the doors, firing positions inside, the fireteam
    [
        ["object", "Land_CncBarrier_stripes_F", [-0.75, -5.5, -2.7], 180, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-1.1, -1.9, -2.7], 180, []],
        ["guard", "rifleman", [-1.1, -0.5, -2.7], 180, []],
        ["object", "Land_BagFence_Short_F", [-1.3, 6.6, -2.7], 0, []],
        ["guard", "mg_gunner", [-1.3, 6, -2.7], 0, []]
    ],
    // Tier 4: wire, top floor positions, barricades on the approaches, the squad
    [
        ["object", "Land_Razorwire_F", [6.8, 0, -2.7], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [-6.8, 0, -2.7], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [4.15, -6.9, -2.7], 180, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [0.55, -8.3, -2.7], 180, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [2.65, -9.9, -2.7], 225, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [0.1, 12.45, -2.7], 45, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [4.5, 12.45, -2.7], 45, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-1.2, -4.1, 1.2], 180, []],
        ["guard", "rifleman", [-1.2, -3.5, 1.2], 180, []],
        ["guard", "officer", [1.6, 2.1, 1.2], 180, []]
    ],
    // Tier 5: the perimeter and its gate, reinforced rooms, the marksman and AT man
    [
        ["object", "Land_HBarrier_5_F", [-5.71, -14.1, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-1.93, -14.1, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-0.54, -14.1, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [5.91, -14.1, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [8.24, -14.1, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-5.7, 14.1, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [0.5, 14.1, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_3_F", [5.5, 14.1, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_1_F", [8.1, 14.1, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.8, -9.84, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.8, -3.72, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.8, 2.4, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.8, 8.52, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [8.8, 12.24, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.8, -9.84, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.8, -3.72, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.8, 2.4, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.8, 8.52, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-8.8, 12.24, -2.7], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-0.45, -12.3, -2.7], 180, ["outside"]],
        ["guard", "at", [3.75, -12.5, -2.7], 180, ["outside"]],
        ["object", "Land_BagFence_Long_F", [0, 1.5, -2.7], 180, []],
        ["object", "Land_BagFence_Long_F", [0, 0.5, 1.2], 180, []],
        ["guard", "marksman", [2.6, -3.4, 1.2], 180, []]
    ]
]
