/*
    Description:
    Mayor's office defence template for Land_i_Shop_02_V1_F (and the classes OT_fnc_officeTemplateKey maps
    to "i_Shop_02_V1_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 3/5/7/9/11.
    Altis large shop: the shop floor with a flat above, a terrace along the south edge and a
    balcony over the west door, the only outside door.
    Generated by tools/officegen/gen_shops.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
*/

[
    // Tier 1: guard posts
    [
        ["guard", "gendarme", [-7, -1.6, -2.6], 270, ["outside"]],
        ["guard", "gendarme", [-1.4, -0.7, -2.6], 270, []],
        ["guard", "gendarme", [-6.7, 1.2, 1.4], 270, []]
    ],
    // Tier 2: sandbags at the doors, a military pair
    [
        ["object", "Land_BagFence_Long_F", [-8.5, -3.2, -2.6], 270, ["outside"]],
        ["guard", "rifleman", [-7.6, -4, -2.6], 270, ["outside"]],
        ["guard", "autorifleman", [-7.6, -2.4, -2.6], 270, ["outside"]]
    ],
    // Tier 3: barriers at the doors, firing positions inside, the fireteam
    [
        ["object", "Land_CncBarrier_stripes_F", [-8.5, -0.3, -2.6], 270, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-2.2, 4.5, -2.6], 0, []],
        ["guard", "rifleman", [-2.2, 3.9, -2.6], 0, []],
        ["object", "Land_BagFence_Short_F", [-5.4, -2.9, 1.3], 270, []],
        ["guard", "mg_gunner", [-4.8, -2.9, 1.3], 270, []]
    ],
    // Tier 4: wire, top floor positions, barricades on the approaches, the squad
    [
        ["object", "Land_Razorwire_F", [0, 7.4, -2.6], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [0, -7.4, -2.6], 180, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-9.9, -5.2, -2.6], 270, ["outside"]],
        ["object", "Land_BagFence_Short_F", [5.2, -3.7, 1.3], 90, []],
        ["guard", "rifleman", [4.6, -3.7, 1.3], 90, []],
        ["guard", "officer", [-1.2, 2, 1.3], 270, []]
    ],
    // Tier 5: the perimeter and its gate, reinforced rooms, the marksman and AT man
    [
        ["object", "Land_HBarrier_5_F", [-9.6, -9.4, -2.6], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-3.6, -9.4, -2.6], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [2.4, -9.4, -2.6], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.4, -9.4, -2.6], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [12, -9.4, -2.6], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9.6, 9.4, -2.6], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-3.6, 9.4, -2.6], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [2.4, 9.4, -2.6], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.4, 9.4, -2.6], 0, ["outside"]],
        ["object", "Land_HBarrier_1_F", [12, 9.4, -2.6], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [12.6, -5.07, -2.6], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [12.6, 1.2, -2.6], 90, ["outside"]],
        ["object", "Land_HBarrier_3_F", [12.6, 6.27, -2.6], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-12.6, -7.45, -2.6], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-12.6, -5.95, -2.6], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-12.6, 1.75, -2.6], 270, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-12.6, 6.45, -2.6], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-10.8, -0.6, -2.6], 270, ["outside"]],
        ["guard", "at", [-11, -4.8, -2.6], 270, ["outside"]],
        ["object", "Land_BagFence_Long_F", [-3.2, -1.6, -2.6], 270, []],
        ["object", "Land_BagFence_Short_F", [0.5, 2, 1.3], 270, []],
        ["object", "Land_BagFence_Short_F", [-0.8, -4.9, 1.3], 180, []],
        ["guard", "marksman", [-0.8, -3.8, 1.3], 180, []]
    ]
]
