/*
    Description:
    Mayor's office defence template for Land_i_House_Big_01_V1_F (and the classes OT_fnc_officeTemplateKey maps
    to "i_House_Big_01_V1_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 2/4/6/8/10.
    Generated by tools/officegen/gen_templates.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
        (kind "doorway": a marker of a real entrance for the checks, nothing is spawned for it)
*/

[
    // Tier 1: the doorways, the office, the flag, the gendarmes
    [
        ["doorway", "main", [-3.3, -7.35, -2.5], 180, [2.25, 0]],
        ["doorway", "side", [4.9, 5.62, -2.5], 90, [1, 1]],
        ["object", "Land_TableDesk_F", [-2, 5.6, -2.5], 180, []],
        ["object", "Land_OfficeChair_01_F", [-2, 4, -2.5], 180, []],
        ["object", "Land_MapBoard_F", [-2, 7.25, -2.5], 180, []],
        ["object", "Flag_NATO_F", [0, -8.35, -2.5], 180, ["outside", "flag"]],
        ["guard", "gendarme", [-0.7, -0.5, -2.4], 200.78, []],
        ["guard", "gendarme", [0.7, 5.8, -2.5], 0, []]
    ],
    // Tier 2: the nest at the main door with the military pair, pairs of bags at the side doors
    [
        ["object", "Land_BagFence_Long_F", [-3.3, -10.35, -2.5], 180, ["outside", "axis"]],
        ["object", "Land_BagFence_Short_F", [-1.6, -9.4, -2.5], 270, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-5, -9.4, -2.5], 270, ["outside"]],
        ["guard", "rifleman", [-2.7, -9.22, -2.5], 180, ["outside"]],
        ["guard", "autorifleman", [-3.9, -9.22, -2.5], 180, ["outside"]],
        ["object", "Land_BagFence_Short_F", [6.1, 7.62, -2.5], 90, ["outside"]],
        ["object", "Land_BagFence_Short_F", [6.1, 3.62, -2.5], 90, ["outside"]]
    ],
    // Tier 3: the back door's post, firing posts at the side doors, window posts
    [
        ["object", "Land_HBarrier_3_F", [0.9, -9.85, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-7.5, -9.85, -2.5], 180, ["outside"]],
        ["guard", "rifleman", [4.1, -5.25, -2.5], 90, ["free"]],
        ["object", "Land_HBarrier_3_F", [7.5, 1.42, -2.5], 90, ["outside"]],
        ["guard", "autorifleman", [5.72, 1.42, -2.5], 90, ["outside"]]
    ],
    // Tier 4: wire on the doorless sides, the stoppers on the approach, the gunner on the balcony, an upstairs post
    [
        ["object", "Land_Razorwire_F", [0.5, 10, -2.5], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [-7, 0, -2.5], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-3.3, -20.35, -2.5], 180, ["outside", "axis"]],
        ["object", "Land_CzechHedgehog_01_F", [-0.5, -19.55, -2.5], 225, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [-6.1, -19.55, -2.5], 225, ["outside"]],
        ["guard", "mg_gunner", [3.6, 6, 0.9], 90, []],
        ["guard", "rifleman", [4.1, -5.25, 0.9], 90, ["free"]]
    ],
    // Tier 5: the perimeter and its gate with the AT man, the airlock, the office's cover, the marksman
    [
        ["object", "Land_HBarrier_1_F", [-8.33, -24.35, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-6.98, -24.35, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [2.88, -24.35, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [8.03, -24.35, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-6.03, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-0.07, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [5.88, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_1_F", [9.43, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, -20.12, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, -14.06, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, -8, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, -1.95, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, 4.11, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_3_F", [10, 8.97, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9, -20.12, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9, -14.06, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9, -8, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9, -1.95, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9, 4.11, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-9, 8.97, -2.5], 270, ["outside"]],
        ["object", "Land_BarGate_F", [-3.3, -24.35, -2.5], 180, ["outside", "axis", "gate"]],
        ["object", "Land_BagFence_Short_F", [2.9, 4.42, -2.5], 270, []],
        ["guard", "at", [0.9, -22.57, -2.5], 180, ["outside"]],
        ["guard", "marksman", [4.1, -2.12, 0.9], 90, ["free"]]
    ]
]
