/*
    Description:
    Mayor's office defence template for Land_Offices_01_V1_F (and the classes OT_fnc_officeTemplateKey maps
    to "Offices_01_V1_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 4/6/8/10/12.
    The five-storey office block: only the east tower section is enterable, the roof is one open terrace.
    Generated by tools/officegen/gen_templates.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
        (kind "doorway": a marker of a real entrance for the checks, nothing is spawned for it)
*/

[
    // Tier 1: the doorways, the office, the flag, the gendarmes
    [
        ["doorway", "main", [10.46, -7.7, -6.7], 180, [2.93, 0]],
        ["doorway", "back", [-14.8, 8.4, -6.7], 0, [1.25, 4]],
        ["object", "Land_TableDesk_F", [10, -1.6, 5], 0, []],
        ["object", "Land_OfficeChair_01_F", [10, 0, 5], 0, []],
        ["object", "Land_MapBoard_F", [8.65, -1, 5], 90, []],
        ["object", "Flag_NATO_F", [13.76, -8.7, -6.7], 180, ["outside", "flag"]],
        ["guard", "gendarme", [12.1, -6.9, -6.7], 90, []],
        ["guard", "gendarme", [-9.4, 7.5, -6.7], 0, []],
        ["guard", "gendarme", [7.9, -6.9, -6.7], 107.34, []],
        ["guard", "gendarme", [-4.4, 7.7, -6.7], 0, []],
        ["object", "Land_WaterCooler_01_new_F", [12.4, -1.4, -6.7], 270, []],
        ["object", "Land_CampingChair_V2_F", [-11, 5.1, -6.7], 0, []],
        ["object", "Land_CampingChair_V2_F", [-12, 5.1, -6.7], 0, []],
        ["object", "Land_OfficeCabinet_01_F", [-6, 4.95, -6.7], 0, []],
        ["object", "Land_OfficeCabinet_01_F", [-7, 4.95, -6.7], 0, []]
    ],
    // Tier 2: the nest at the main door with the military pair, pairs of bags at the side doors
    [
        ["object", "Land_BagFence_Long_F", [10.46, -10.7, -6.7], 180, ["outside", "axis"]],
        ["object", "Land_BagFence_Short_F", [12.16, -9.75, -6.7], 270, ["outside"]],
        ["object", "Land_BagFence_Short_F", [8.76, -9.75, -6.7], 270, ["outside"]],
        ["guard", "rifleman", [11.06, -9.57, -6.7], 180, ["outside"]],
        ["guard", "autorifleman", [9.86, -9.57, -6.7], 180, ["outside"]]
    ],
    // Tier 3: the back door's post, firing posts at the side doors, window posts
    [
        ["object", "Land_BagFence_Short_F", [-14.8, 10.6, -6.7], 0, ["outside", "axis"]],
        ["guard", "rifleman", [-14.8, 9.48, -6.7], 0, ["free"]],
        ["guard", "autorifleman", [12.2, -1.7, 5], 90, []],
        ["object", "Land_CampingTable_F", [5.3, 2.4, 5], 90, []],
        ["object", "Land_PortableLongRangeRadio_F", [5.3, 2.4, 5.76], 90, []],
        ["object", "Land_CampingChair_V2_F", [4.5, 2.4, 5], 90, []],
        ["object", "MapBoard_altis_F", [5.5, 3.9, 5], 180, []]
    ],
    // Tier 4: wire on the doorless sides, the stoppers on the approach, the gunner on the balcony, an upstairs post
    [
        ["object", "Land_Razorwire_F", [16, -5.45, -6.7], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [16, 2.45, -6.7], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [-20, -5.45, -6.7], 270, ["outside"]],
        ["object", "Land_Razorwire_F", [-20, 2.45, -6.7], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [10.46, -20.7, -6.7], 180, ["outside", "axis"]],
        ["object", "Land_CzechHedgehog_01_F", [13.26, -19.9, -6.7], 225, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [7.66, -19.9, -6.7], 225, ["outside"]],
        ["guard", "mg_gunner", [12.4, -6.9, 5], 90, []],
        ["guard", "rifleman", [6.6, -7, 1], 180, []]
    ],
    // Tier 5: the perimeter and its gate with the AT man, the airlock, the office's cover, the marksman
    [
        ["object", "Land_HBarrier_5_F", [-19.95, -26.7, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-13.86, -26.7, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-7.77, -26.7, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-1.68, -26.7, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [4.42, -26.7, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [15.45, -26.7, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [18.22, -26.7, -6.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-20, 15, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-14, 15, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8, 15, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-2, 15, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [4, 15, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, 15, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [16, 15, -6.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [19, -22.44, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [19, -16.33, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [19, -10.22, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [19, -4.11, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [19, 2.01, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [19, 8.12, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [19, 11.83, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [19, 13.14, -6.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23, -22.44, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23, -16.33, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23, -10.22, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23, -4.11, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23, 2.01, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23, 8.12, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-23, 11.83, -6.7], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-23, 13.14, -6.7], 270, ["outside"]],
        ["object", "Land_BarGate_F", [10.46, -26.7, -6.7], 180, ["outside", "axis", "gate"]],
        ["object", "Land_BagFence_Short_F", [9.06, -5.5, -6.7], 0, []],
        ["object", "Land_BagFence_Long_F", [10, -3.8, 5], 180, []],
        ["guard", "at", [6.26, -25.2, -6.7], 180, ["outside"]],
        ["guard", "at", [3.9, -4, 1], 270, ["free"]]
    ]
]
