/*
    Description:
    Mayor's office defence template for Land_i_Shop_01_V1_F (and the classes OT_fnc_officeTemplateKey maps
    to "i_Shop_01_V1_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 2/4/6/8/10.
    Generated by tools/officegen/gen_templates.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
        (kind "doorway": a marker of a real entrance for the checks, nothing is spawned for it)
*/

[
    // Tier 1: the doorways, the office, the flag, the gendarmes
    [
        ["doorway", "main", [2.98, -2.6, -2.7], 180, [1, 1]],
        ["doorway", "back", [2.3, 7.2, -2.7], 0, [1.25, 2]],
        ["object", "Land_TableDesk_F", [-1.4, 2, -2.7], 270, []],
        ["object", "Land_OfficeChair_01_F", [-3, 2, -2.7], 270, []],
        ["object", "Land_MapBoard_F", [0, 4.35, -2.7], 180, []],
        ["object", "Flag_NATO_F", [6.28, -3.6, -2.7], 180, ["outside", "flag"]],
        ["guard", "gendarme", [-1.1, -0.5, -2.7], 117.26, []],
        ["guard", "gendarme", [3.2, 4.5, -2.7], 90, []]
    ],
    // Tier 2: the nest at the main door with the military pair, pairs of bags at the side doors
    [
        ["object", "Land_BagFence_Long_F", [2.98, -5.6, -2.7], 180, ["outside", "axis"]],
        ["object", "Land_BagFence_Short_F", [4.68, -4.65, -2.7], 270, ["outside"]],
        ["object", "Land_BagFence_Short_F", [1.28, -4.65, -2.7], 270, ["outside"]],
        ["guard", "rifleman", [3.58, -4.47, -2.7], 180, ["outside"]],
        ["guard", "autorifleman", [2.38, -4.47, -2.7], 180, ["outside"]]
    ],
    // Tier 3: the back door's post, firing posts at the side doors, window posts
    [
        ["object", "Land_BagFence_Short_F", [2.3, 9.4, -2.7], 0, ["axis"]],
        ["guard", "rifleman", [2.3, 8.28, -2.7], 0, ["free"]],
        ["guard", "autorifleman", [-2.6, 4.8, -2.7], 270, []]
    ],
    // Tier 4: wire on the doorless sides, the stoppers on the approach, the gunner on the balcony, an upstairs post
    [
        ["object", "Land_Razorwire_F", [7, 2.5, -2.7], 90, ["outside"]],
        ["object", "Land_Razorwire_F", [-7, 2.5, -2.7], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [2.98, -15.6, -2.7], 180, ["outside", "axis"]],
        ["object", "Land_CzechHedgehog_01_F", [5.78, -14.8, -2.7], 225, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [0.18, -14.8, -2.7], 225, ["outside"]],
        ["guard", "mg_gunner", [-1.3, 6, -2.7], 0, []],
        ["guard", "rifleman", [0.9, 4.2, -2.7], 163.03, []]
    ],
    // Tier 5: the perimeter and its gate with the AT man, the airlock, the office's cover, the marksman
    [
        ["object", "Land_HBarrier_5_F", [-5.49, -21.6, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-1.86, -21.6, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-0.64, -21.6, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [6.61, -21.6, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [7.87, -21.6, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-5.47, 13.5, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [0.57, 13.5, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_3_F", [5.42, 13.5, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_1_F", [7.88, 13.5, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.5, -17.38, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.5, -11.34, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.5, -5.29, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.5, 0.75, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.5, 6.79, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [8.5, 10.44, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [8.5, 11.68, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.5, -17.38, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.5, -11.34, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.5, -5.29, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.5, 0.75, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.5, 6.79, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-8.5, 10.44, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-8.5, 11.68, -2.7], 270, ["outside"]],
        ["object", "Land_BarGate_F", [2.98, -21.6, -2.7], 180, ["outside", "axis", "gate"]],
        ["object", "Land_BagFence_Short_F", [1.57, -0.4, -2.7], 0, []],
        ["object", "Land_BagFence_Long_F", [0.8, 2, -2.7], 90, []],
        ["guard", "at", [-1.23, -20.1, -2.7], 180, ["outside"]],
        ["guard", "marksman", [1.6, 2.1, 1.1], 90, []]
    ]
]
