/*
    Description:
    Mayor's office defence template for Land_Research_HQ_F (and the classes OT_fnc_officeTemplateKey maps
    to "Research_HQ_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 3/5/7/9/11.
    Generated by tools/officegen/gen_templates.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
        (kind "doorway": a marker of a real entrance for the checks, nothing is spawned for it)
*/

[
    // Tier 1: the doorways, the office, the flag, the gendarmes
    [
        ["doorway", "main", [-4.4, 0.58, -2.4], 270, [1.5, 0]],
        ["object", "Land_TableDesk_F", [2, 2.4, -2.4], 0, []],
        ["object", "Land_OfficeChair_01_F", [2, 4, -2.4], 0, []],
        ["object", "Land_MapBoard_F", [0, 4.35, -2.4], 180, []],
        ["object", "Flag_NATO_F", [-5.4, 3.88, -2.4], 270, ["outside", "flag"]],
        ["guard", "gendarme", [-5, 0.9, -2.4], 270, []],
        ["guard", "gendarme", [-1.3, -5.8, -2.7], 180, []],
        ["guard", "gendarme", [4.8, 5.2, -2.6], 0, []]
    ],
    // Tier 2: the nest at the main door with the military pair, pairs of bags at the side doors
    [
        ["object", "Land_BagFence_Long_F", [-7.4, 0.57, -2.4], 270, ["outside", "axis"]],
        ["object", "Land_BagFence_Short_F", [-6.45, -1.12, -2.4], 0, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-6.45, 2.27, -2.4], 0, ["outside"]],
        ["guard", "rifleman", [-6.28, -0.03, -2.4], 270, ["outside"]],
        ["guard", "autorifleman", [-6.28, 1.17, -2.4], 270, ["outside"]]
    ],
    // Tier 3: the back door's post, firing posts at the side doors, window posts
    [
        ["object", "Land_HBarrier_3_F", [-6.9, -3.63, -2.4], 270, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-6.9, 4.78, -2.4], 270, ["outside"]],
        ["guard", "rifleman", [8.2, -1.7, -2.3], 90, []],
        ["guard", "autorifleman", [8.2, -1.9, -0.5], 90, []]
    ],
    // Tier 4: wire on the doorless sides, the stoppers on the approach, the gunner on the balcony, an upstairs post
    [
        ["object", "Land_Razorwire_F", [1.5, -9, -2.4], 180, ["outside"]],
        ["object", "Land_Razorwire_F", [1.5, 9, -2.4], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [11, 0, -2.4], 90, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-17.4, 0.57, -2.4], 270, ["outside", "axis"]],
        ["object", "Land_CzechHedgehog_01_F", [-16.6, -2.23, -2.4], 315, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [-16.6, 3.37, -2.4], 315, ["outside"]],
        ["guard", "mg_gunner", [-5, 1, -0.5], 270, ["free"]],
        ["guard", "rifleman", [2.7, 5.3, -0.5], 0, []]
    ],
    // Tier 5: the perimeter and its gate with the AT man, the airlock, the office's cover, the marksman
    [
        ["object", "Land_HBarrier_5_F", [-20.41, -10.5, -2.4], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-14.43, -10.5, -2.4], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.44, -10.5, -2.4], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-2.46, -10.5, -2.4], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [3.53, -10.5, -2.4], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [9.51, -10.5, -2.4], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-20.41, 10.5, -2.4], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-14.43, 10.5, -2.4], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-8.44, 10.5, -2.4], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-2.46, 10.5, -2.4], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [3.53, 10.5, -2.4], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [9.51, 10.5, -2.4], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [12.5, -6.2, -2.4], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [12.5, 0, -2.4], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [12.5, 6.2, -2.4], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-23.4, -5.86, -2.4], 270, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-23.4, 5.61, -2.4], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-23.4, 8.47, -2.4], 270, ["outside"]],
        ["object", "Land_BarGate_F", [-23.4, 0.58, -2.4], 270, ["outside", "axis", "gate"]],
        ["object", "Land_BagFence_Short_F", [-2.2, 1.98, -2.4], 90, []],
        ["object", "Land_BagFence_Short_F", [-2.2, -0.82, -2.4], 90, []],
        ["object", "Land_BagFence_Long_F", [2, 0.2, -2.4], 180, []],
        ["guard", "at", [-21.9, -3.62, -2.4], 270, ["outside"]],
        ["guard", "marksman", [-3.5, 2, -0.5], 270, []]
    ]
]
