/*
    Description:
    Mayor's office defence template for Land_i_House_Big_02_V1_F (and the classes OT_fnc_officeTemplateKey maps
    to "i_House_Big_02_V1_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 2/4/6/8/10.
    Generated by tools/officegen/gen_templates.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
*/

[
    // Tier 1: guard posts
    [
        ["object", "Flag_NATO_F", [-5.9, -7.6, -2.5], 270, ["outside", "flag"]],
        ["object", "Land_TableDesk_F", [1.45, -1, -2.5], 270, []],
        ["object", "Land_OfficeChair_01_F", [2.25, -1, -2.5], 270, []],
        ["guard", "gendarme", [0.1, -3.3, -2.5], 251.57, []],
        ["guard", "gendarme", [3.5, -5.7, -2.5], 180, []]
    ],
    // Tier 2: sandbags at the doors, a military pair
    [
        ["object", "Land_BagFence_Short_F", [-5.5, -2.3, -2.5], 270, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-5.5, -6.3, -2.5], 270, ["outside"]],
        ["object", "Land_BagFence_Short_F", [2.1, 7.9, -2.5], 0, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-1.9, 7.9, -2.5], 0, ["outside"]],
        ["guard", "rifleman", [-5.2, -3.3, -2.5], 270, ["outside"]],
        ["guard", "autorifleman", [-5.2, -5.3, -2.5], 270, ["outside"]]
    ],
    // Tier 3: barriers at the doors, firing positions inside, the fireteam
    [
        ["object", "Land_HBarrier_3_F", [-7.3, -1.9, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_3_F", [2.5, 9.7, -2.5], 0, ["outside"]],
        ["guard", "rifleman", [3.3, 4.4, -2.5], 0, []],
        ["guard", "autorifleman", [-6, -1.9, -2.5], 270, ["outside"]]
    ],
    // Tier 4: wire, top floor positions, barricades on the approaches, the squad
    [
        ["object", "Land_Razorwire_F", [0.5, -9, -2.5], 180, ["outside"]],
        ["object", "Land_Razorwire_F", [8, 0.5, -2.5], 90, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-8.7, -6.3, -2.5], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-10.5, -2.7, -2.5], 270, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [-12.3, -4.8, -2.5], 315, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-1.9, 11.1, -2.5], 0, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [1.7, 12.9, -2.5], 0, ["outside"]],
        ["guard", "mg_gunner", [-0.6, -5.3, 1], 180, []],
        ["guard", "rifleman", [3.3, 6.3, 1], 0, []]
    ],
    // Tier 5: the perimeter and its gate, reinforced rooms, the marksman and AT man
    [
        ["object", "Land_HBarrier_5_F", [-12.83, -11, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-6.69, -11, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-0.55, -11, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [5.59, -11, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [9.33, -11, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-12.83, 18.3, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-6.69, 18.3, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-0.55, 18.3, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [5.59, 18.3, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_1_F", [9.33, 18.3, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, -6.76, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, -0.67, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, 5.41, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [10, 11.49, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [10, 15.18, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [10, 16.46, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-15.9, -8.05, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-15.9, 0.73, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-15.9, 6.78, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-15.9, 12.83, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-15.9, 16.48, -2.5], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-14.1, -1.7, -2.5], 270, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-0.7, -2.9, -2.5], 90, []],
        ["object", "Land_BagFence_Short_F", [-0.7, -5.7, -2.5], 90, []],
        ["guard", "marksman", [4.2, 2.9, 1], 90, []],
        ["guard", "at", [-14.3, -5.9, -2.5], 270, ["outside"]]
    ]
]
