/*
    Description:
    Mayor's office defence template for Land_i_House_Big_01_V1_F (and the classes OT_fnc_officeTemplateKey maps
    to "i_House_Big_01_V1_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 2/4/6/8/10.
    Generated by tools/officegen/gen_templates.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
*/

[
    // Tier 1: guard posts
    [
        ["object", "Flag_NATO_F", [1.5, -9.1, -2.5], 180, ["outside", "flag"]],
        ["object", "Land_TableDesk_F", [-2, 4.55, -2.5], 0, []],
        ["object", "Land_OfficeChair_01_F", [-2, 3.75, -2.5], 0, []],
        ["object", "Land_MapBoard_F", [-4, 3.9, -2.5], 0, []],
        ["guard", "gendarme", [-0.7, -0.5, -2.4], 191.11, []],
        ["guard", "gendarme", [0.7, 5.8, -2.5], 0, []]
    ],
    // Tier 2: sandbags at the doors, a military pair
    [
        ["object", "Land_BagFence_Short_F", [-3.8, -8.7, -2.5], 180, ["outside"]],
        ["object", "Land_BagFence_Short_F", [0.2, -8.7, -2.5], 180, ["outside"]],
        ["object", "Land_BagFence_Short_F", [6.5, 3.5, -2.5], 90, ["outside"]],
        ["guard", "rifleman", [-2.8, -8.4, -2.5], 180, ["outside"]],
        ["guard", "autorifleman", [-0.8, -8.4, -2.5], 180, ["outside"]]
    ],
    // Tier 3: barriers at the doors, firing positions inside, the fireteam
    [
        ["object", "Land_HBarrier_3_F", [-4.2, -10.5, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [8.3, 3.1, -2.5], 90, ["outside"]],
        ["guard", "rifleman", [-4.2, -9.2, -2.5], 180, ["outside"]],
        ["guard", "autorifleman", [7, 3.1, -2.5], 90, ["outside"]]
    ],
    // Tier 4: wire, top floor positions, barricades on the approaches, the squad
    [
        ["object", "Land_Razorwire_F", [0.5, 10, -2.5], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [-7, 0, -2.5], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [0.2, -11.9, -2.5], 180, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-3.4, -13.7, -2.5], 180, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [-1.3, -15.5, -2.5], 225, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [9.7, 7.5, -2.5], 90, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [11.5, 3.9, -2.5], 90, ["outside"]],
        ["guard", "mg_gunner", [0.3, 2, 0.9], 90, []],
        ["guard", "rifleman", [3.6, 6, 0.9], 90, []]
    ],
    // Tier 5: the perimeter and its gate, reinforced rooms, the marksman and AT man
    [
        ["object", "Land_HBarrier_3_F", [-7.1, -19.1, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-4.5, -19.1, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [3.19, -19.1, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [9.16, -19.1, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_3_F", [13.94, -19.1, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [16.31, -19.1, -2.5], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-5.93, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [0.21, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [6.35, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [12.49, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_1_F", [16.23, 12, -2.5], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [16.9, -14.91, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [16.9, -8.93, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [16.9, -2.94, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [16.9, 3.04, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_3_F", [16.9, 7.82, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [16.9, 10.21, -2.5], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9, -14.91, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9, -8.93, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9, -2.94, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9, 3.04, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-9, 7.82, -2.5], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-9, 10.21, -2.5], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-4.4, -17.3, -2.5], 180, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-0.4, -3.9, -2.5], 0, []],
        ["object", "Land_BagFence_Long_F", [-2, 6.75, -2.5], 0, []],
        ["guard", "marksman", [-3.6, 5.4, 0.9], 270, []],
        ["guard", "at", [-0.2, -17.5, -2.5], 180, ["outside"]]
    ]
]
