/*
    Description:
    Mayor's office defence template for Land_Research_HQ_F (and the classes OT_fnc_officeTemplateKey maps
    to "Research_HQ_F"): what each defence tier adds, in the building's model coordinates. Tier N in
    play is tiers 1..N together (OT_fnc_officeApplyTemplate). Guards at the five tiers: 3/5/7/9/11.
    Altis research HQ: glass-walled, two levels, the entrance on the west under a canopy. The
    mayor's office (desk, map, radio) is upstairs in the north-east corner, the occupier's flag outside.
    Generated by tools/officegen/gen_shops.py from tools/officegen/probe_offices.txt, edit the
    generator rather than this file.

    Returns: ARRAY - [tier 1 additions, ..., tier 5 additions], each [[kind, class or role, [x, y, z], dir, extra], ...]
*/

[
    // Tier 1: guard posts
    [
        ["object", "Land_TableDesk_F", [5.6, 3, -0.5], 270, []],
        ["object", "Land_OfficeChair_01_F", [6.5, 3, -0.5], 270, []],
        ["object", "Land_MapBoard_F", [5.4, 5.7, -0.5], 180, []],
        ["object", "Land_PortableLongRangeRadio_F", [6.8, 4.6, -0.5], 270, []],
        ["object", "Land_OfficeCabinet_01_F", [7, 5.4, -0.5], 180, []],
        ["object", "Flag_NATO_F", [-10.2, 5.5, -2.7], 270, ["outside", "flag"]],
        ["guard", "gendarme", [-6, -4.6, -2.7], 270, ["outside"]],
        ["guard", "gendarme", [-5, 0.9, -2.4], 270, []],
        ["guard", "gendarme", [-1.4, -5.4, -0.5], 180, []]
    ],
    // Tier 2: sandbags at the doors, a military pair
    [
        ["object", "Land_BagFence_Long_F", [-7, -2.3, -2.7], 270, ["outside"]],
        ["guard", "rifleman", [-6.1, -3.1, -2.7], 270, ["outside"]],
        ["guard", "autorifleman", [-6.1, -1.5, -2.7], 270, ["outside"]]
    ],
    // Tier 3: barriers at the doors, firing positions inside, the fireteam
    [
        ["object", "Land_CncBarrier_stripes_F", [-7, -5.2, -2.7], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-7, 0.6, -2.7], 270, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-1.3, -6.4, -2.7], 180, []],
        ["guard", "rifleman", [-1.3, -5.8, -2.7], 180, []],
        ["object", "Land_BagFence_Short_F", [4.8, 6, -2.6], 0, []],
        ["guard", "mg_gunner", [4.8, 5.2, -2.6], 0, []]
    ],
    // Tier 4: wire, top floor positions, barricades on the approaches, the squad
    [
        ["object", "Land_Razorwire_F", [0, 8.7, -2.7], 0, ["outside"]],
        ["object", "Land_Razorwire_F", [0, -8.7, -2.7], 180, ["outside"]],
        ["object", "Land_Razorwire_F", [10.9, 0, -2.7], 90, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-8.4, -4.3, -2.7], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-9.8, -0.7, -2.7], 270, ["outside"]],
        ["object", "Land_CzechHedgehog_01_F", [-11.4, -2.8, -2.7], 315, ["outside"]],
        ["object", "Land_BagFence_Short_F", [-4.1, 2, -0.5], 270, []],
        ["guard", "officer", [-3.5, 2, -0.5], 270, []],
        ["object", "Land_BagFence_Short_F", [-4, -3.4, -0.5], 270, []],
        ["guard", "rifleman", [-3.4, -3.4, -0.5], 270, []]
    ],
    // Tier 5: the perimeter and its gate, reinforced rooms, the marksman and AT man
    [
        ["object", "Land_HBarrier_5_F", [-9.84, -10.7, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-3.72, -10.7, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [2.4, -10.7, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.52, -10.7, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_1_F", [12.24, -10.7, -2.7], 180, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-9.84, 10.7, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-3.72, 10.7, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [2.4, 10.7, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [8.52, 10.7, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_1_F", [12.24, 10.7, -2.7], 0, ["outside"]],
        ["object", "Land_HBarrier_5_F", [12.9, -6.53, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [12.9, -0.57, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_5_F", [12.9, 5.38, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_1_F", [12.9, 8.93, -2.7], 90, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-12.9, -7.6, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_1_F", [-12.9, -5, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_5_F", [-12.9, 2.75, -2.7], 270, ["outside"]],
        ["object", "Land_HBarrier_3_F", [-12.9, 7.65, -2.7], 270, ["outside"]],
        ["object", "Land_CncBarrier_stripes_F", [-11.1, 0.3, -2.7], 270, ["outside"]],
        ["guard", "at", [-11.3, -3.9, -2.7], 270, ["outside"]],
        ["object", "Land_BagFence_Long_F", [-2, -0.5, -2.7], 270, []],
        ["object", "Land_BagFence_Short_F", [3.6, 1, -0.5], 270, []],
        ["object", "Land_BagFence_Short_F", [3.4, 5.9, -0.5], 0, []],
        ["guard", "marksman", [2.7, 5.3, -0.5], 0, []]
    ]
]
