"""
The occupier compounds' areas (tools/officegen/COMPOUND_PLAN.md): merged from the compound editor's lines in an RPT
(or a file of them) into tools/officegen/compounds/<world>.txt, then written as the mod's data function
(addons/overthrow_main/functions/offices/compounds/fn_officeCompounds_<world>.sqf, read by OT_fnc_officeCompound).
A town's tier saved again replaces the earlier save; everything else is kept.

Lines (world x, y; a polygon's vertices in order round it):
    OTCOMPOUND|world|town|tier|[[x,y],[x,y],...]
    OTCOMPOUND|world|town|CONFIRMED

Usage (from the repository root):
    python tools/officegen/merge_compounds.py [rpt or file]   the newest RPT when left out
    python tools/officegen/merge_compounds.py --seed tools/officegen/compounds/<Town>_proposal.json
        a proposal (metres east and north of the office, from the block probe) as the town's areas
    python tools/officegen/merge_compounds.py --write          only rewrites the data function
"""
import glob
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SAVED = os.path.join(ROOT, "tools", "officegen", "compounds")
OUT = os.path.join(ROOT, "addons", "overthrow_main", "functions", "offices", "compounds")


def parse(lines):
    worlds = {}
    for line in lines:
        f = line.split("|")
        if len(f) < 4 or f[0] != "OTCOMPOUND":
            continue
        t = worlds.setdefault(f[1], {}).setdefault(f[2], {"tiers": {}, "confirmed": False})
        if f[3] == "CONFIRMED":
            t["confirmed"] = True
        elif len(f) >= 5:
            t["tiers"][int(f[3])] = [[float(v) for v in p.split(",")] for p in re.findall(r"\[([^\[\]]+)\]", f[4])]
    return worlds


def saved_path(world):
    return os.path.join(SAVED, f"{world}.txt")


def load_saved(world):
    p = saved_path(world)
    return parse(open(p, encoding="utf-8").read().splitlines()).get(world, {}) if os.path.exists(p) else {}


def poly(points):
    return "[" + ",".join(f"[{x:.2f},{y:.2f}]" for x, y in points) + "]"


def write_saved(world, towns):
    os.makedirs(SAVED, exist_ok=True)
    lines = []
    for town in sorted(towns):
        t = towns[town]
        for n in sorted(t["tiers"]):
            lines.append(f"OTCOMPOUND|{world}|{town}|{n}|{poly(t['tiers'][n])}")
        if t.get("confirmed"):
            lines.append(f"OTCOMPOUND|{world}|{town}|CONFIRMED")
    open(saved_path(world), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")


def write_sqf(world, towns):
    os.makedirs(OUT, exist_ok=True)
    rows = []
    for town in sorted(towns):
        tiers = [poly(towns[town]["tiers"].get(n, [])) for n in (3, 4, 5)]
        rows.append(f'    ["{town}", [{", ".join(tiers)}]]')
    text = (
        "/*\n"
        f"    The occupier compounds' areas in {world}'s towns (OT_fnc_officeCompound): per town, the tier 3, 4 and 5\n"
        "    polygons (world [x, y], [] for a tier without one). Generated by tools/officegen/merge_compounds.py from\n"
        f"    tools/officegen/compounds/{world}.txt: don't edit by hand.\n"
        "*/\n\n"
        "createHashMapFromArray [\n" + ",\n".join(rows) + ("\n" if rows else "") + "]\n"
    )
    path = os.path.join(OUT, f"fn_officeCompounds_{world}.sqf")
    open(path, "w", encoding="utf-8", newline="\n").write(text)
    return path


def rpt_lines(path):
    out = []
    for line in open(path, encoding="utf-8", errors="replace"):
        m = re.search(r'"(OTCOMPOUND\|.*)"\s*$', line) or re.match(r"(OTCOMPOUND\|.*?)\s*$", line)
        if m:
            out.append(m.group(1))
    return out


def main(argv):
    world = "Altis"
    if "--write" in argv:
        print("wrote", os.path.relpath(write_sqf(world, load_saved(world)), ROOT))
        return 0
    if "--seed" in argv:
        sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
        import blocklib
        prop = json.load(open(argv[argv.index("--seed") + 1], encoding="utf-8"))
        b = blocklib.load(world)[prop["town"]]
        towns = load_saved(world)
        t = towns.setdefault(prop["town"], {"tiers": {}, "confirmed": False})
        for key, pts in prop.items():
            if re.fullmatch(r"T[345]", key):
                t["tiers"][int(key[1])] = [[b.pos[0] + x, b.pos[1] + y] for x, y in pts]
        write_saved(world, towns)
        print(f"{prop['town']}: tiers {sorted(t['tiers'])} seeded; wrote", os.path.relpath(write_sqf(world, towns), ROOT))
        return 0
    paths = [a for a in argv if not a.startswith("-")]
    src = paths[0] if paths else max(glob.glob(os.path.join(os.environ.get("LOCALAPPDATA", ""), "Arma 3", "*.rpt")), key=os.path.getmtime)
    new = parse(rpt_lines(src)).get(world, {})
    towns = load_saved(world)
    for town, t in new.items():
        s = towns.setdefault(town, {"tiers": {}, "confirmed": False})
        s["tiers"].update(t["tiers"])
        s["confirmed"] = s["confirmed"] or t["confirmed"]
        print(f"{town}: tiers saved {sorted(t['tiers'])}{', confirmed' if t['confirmed'] else ''}")
    write_saved(world, towns)
    print("wrote", os.path.relpath(write_sqf(world, towns), ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
