"""
Merges the mayor's office layouts saved in towns (the "townlayout" QA suite's OTLAYOUT lines) from an RPT
into tools/officegen/layouts/<world>.txt, then writes the mod's data function from it
(addons/overthrow_main/functions/offices/layouts/fn_officeLayouts_<world>.sqf, read by OT_fnc_officeLayout).
A tier saved again replaces the earlier save of that town's tier; everything else is kept.

Lines (the editor logs them on each save, a tier's TIER line first):
    OTLAYOUT|world|town|OFFICE|class|[x,y,z] ASL|direction|spawned (true/false)
    OTLAYOUT|world|town|TIER|n|item count
    OTLAYOUT|world|town|ITEM|n|kind|what|[x,y,z] ASL|orientation|extra (comma separated flags)

Usage (from the repository root):
    python tools/officegen/merge_layouts.py [rpt]    the newest RPT in %LOCALAPPDATA%\\Arma 3 when left out
    python tools/officegen/merge_layouts.py --write  only rewrites the data functions from the saved files
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SAVED = os.path.join(ROOT, "tools", "officegen", "layouts")
OUT = os.path.join(ROOT, "addons", "overthrow_main", "functions", "offices", "layouts")


def parse(lines):
    """{world: {town: {"office": fields, "tiers": {n: [item fields]}}}} from OTLAYOUT lines, later saves winning."""
    worlds = {}
    pending = None  # (world, town, n, expected count, items)

    def close():
        nonlocal pending
        if pending:
            world, town, n, count, items = pending
            if len(items) == count:
                worlds.setdefault(world, {}).setdefault(town, {"office": None, "tiers": {}})["tiers"][n] = items
            else:
                print(f"skipped {world} {town} tier {n}: {len(items)} of {count} items in the RPT")
        pending = None

    for line in lines:
        f = line.split("|")
        if len(f) < 4 or f[0] != "OTLAYOUT":
            continue
        world, town, what = f[1], f[2], f[3]
        if what == "OFFICE":
            close()
            worlds.setdefault(world, {}).setdefault(town, {"office": None, "tiers": {}})["office"] = f[4:8]
        elif what == "TIER":
            close()
            pending = (world, town, int(f[4]), int(f[5]), [])
        elif what == "ITEM" and pending and pending[:3] == (world, town, int(f[4])):
            pending[4].append(f[5:10])
    close()
    return worlds


def rpt_lines(path):
    out = []
    for line in open(path, encoding="utf-8", errors="replace"):
        m = re.search(r'"(OTLAYOUT\|.*)"\s*$', line)
        if m:
            out.append(m.group(1))
    return out


def saved_path(world):
    return os.path.join(SAVED, f"{world}.txt")


def load_saved(world):
    path = saved_path(world)
    if not os.path.exists(path):
        return {}
    return parse(open(path, encoding="utf-8").read().splitlines()).get(world, {})


def write_saved(world, towns):
    os.makedirs(SAVED, exist_ok=True)
    lines = []
    for town in sorted(towns):
        t = towns[town]
        if t["office"]:
            lines.append("|".join(["OTLAYOUT", world, town, "OFFICE"] + t["office"]))
        for n in sorted(t["tiers"]):
            items = t["tiers"][n]
            lines.append("|".join(["OTLAYOUT", world, town, "TIER", str(n), str(len(items))]))
            lines += ["|".join(["OTLAYOUT", world, town, "ITEM", str(n)] + it) for it in items]
    open(saved_path(world), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")


def sqf_item(it):
    kind, what, pos, orient, extra = it
    flags = ",".join(f'"{x}"' for x in extra.split(",") if x)
    return f'["{kind}","{what}",{pos},{orient},[{flags}]]'


def write_sqf(world, towns):
    os.makedirs(OUT, exist_ok=True)
    rows = []
    for town in sorted(towns):
        t = towns[town]
        if not t["office"]:
            continue
        cls, pos, d, spawned = t["office"]
        tiers = ["[" + ",".join(sqf_item(it) for it in t["tiers"].get(n, [])) + "]" for n in range(1, 6)]
        rows.append(f'    ["{town}", [["{cls}", {pos}, {d}, {spawned}], [\n        ' + ",\n        ".join(tiers) + "\n    ]]]")
    text = (
        "/*\n"
        f"    The mayor's office layouts authored in {world}'s towns (OT_fnc_officeLayout). Generated by\n"
        f"    tools/officegen/merge_layouts.py from tools/officegen/layouts/{world}.txt: don't edit by hand.\n"
        "*/\n\n"
        "createHashMapFromArray [\n" + ",\n".join(rows) + ("\n" if rows else "") + "]\n"
    )
    path = os.path.join(OUT, f"fn_officeLayouts_{world}.sqf")
    open(path, "w", encoding="utf-8", newline="\n").write(text)
    return path


def main(argv):
    if "--write" in argv:
        worlds = {os.path.splitext(os.path.basename(p))[0]: None for p in glob.glob(os.path.join(SAVED, "*.txt"))}
        for world in worlds:
            print("wrote", os.path.relpath(write_sqf(world, load_saved(world)), ROOT))
        return 0
    paths = [a for a in argv if not a.startswith("-")]
    if paths:
        rpt = paths[0]
    else:
        found = glob.glob(os.path.join(os.environ.get("LOCALAPPDATA", ""), "Arma 3", "*.rpt"))
        if not found:
            sys.exit("no RPT given and none found in %LOCALAPPDATA%\\Arma 3")
        rpt = max(found, key=os.path.getmtime)
    new = parse(rpt_lines(rpt))
    if not new:
        print(f"no OTLAYOUT lines in {rpt}")
        return 1
    for world, towns in new.items():
        saved = load_saved(world)
        for town, t in towns.items():
            s = saved.setdefault(town, {"office": None, "tiers": {}})
            if t["office"]:
                s["office"] = t["office"]
            s["tiers"].update(t["tiers"])
            print(f"{world} {town}: tiers saved {sorted(t['tiers'])}, now {sorted(s['tiers'])}")
        write_saved(world, saved)
        print("wrote", os.path.relpath(write_sqf(world, saved), ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
